import { Skill, ISkill } from "./skill";

export abstract class SkillLibrary {
  static BasicSkills: Skill[] = [
    new Skill({Description: "Art", CharacteristicType: CharacteristicType.Dexterity} as ISkill),
    // new Skill({Description: "Art (Cartography)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Engraving)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Mosaics)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Painting)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Sculpture)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Tattoo)", CharacteristicType: CharacteristicType.Dexterity}),
    // new Skill({Description: "Art (Weaving)", CharacteristicType: CharacteristicType.Dexterity}),
    new Skill({Description: "Athletics", CharacteristicType: CharacteristicType.Agility} as ISkill),
    new Skill({Description: "Bribery", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    new Skill({Description: "Charm", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    new Skill({Description: "Charm Animal", CharacteristicType: CharacteristicType.Willpower} as ISkill),
    new Skill({Description: "Climb", CharacteristicType: CharacteristicType.Strength} as ISkill),
    new Skill({Description: "Consume Alcohol", CharacteristicType: CharacteristicType.Toughness} as ISkill),
    new Skill({Description: "Cool", CharacteristicType: CharacteristicType.Willpower} as ISkill),
    new Skill({Description: "Dodge", CharacteristicType: CharacteristicType.Agility} as ISkill),
    new Skill({Description: "Drive", CharacteristicType: CharacteristicType.Agility} as ISkill),
    new Skill({Description: "Endurance", CharacteristicType: CharacteristicType.Toughness} as ISkill),
    new Skill({Description: "Entertain", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    // new Skill({Description: "Entertain (Acting)", CharacteristicType: CharacteristicType.Fellowship}),
    // new Skill({Description: "Entertain (Comedy)", CharacteristicType: CharacteristicType.Fellowship}),
    // new Skill({Description: "Entertain (Singing)", CharacteristicType: CharacteristicType.Fellowship}),
    // new Skill({Description: "Entertain (Storytelling)", CharacteristicType: CharacteristicType.Fellowship}),
    new Skill({Description: "Gamble", CharacteristicType: CharacteristicType.Intelligence} as ISkill),
    new Skill({Description: "Gossip", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    new Skill({Description: "Haggle", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    new Skill({Description: "Intimidate", CharacteristicType: CharacteristicType.Strength} as ISkill),
    new Skill({Description: "Intuition", CharacteristicType: CharacteristicType.Initiative} as ISkill),
    new Skill({Description: "Leadership", CharacteristicType: CharacteristicType.Fellowship} as ISkill),
    new Skill({Description: "Melee", CharacteristicType: CharacteristicType.WeaponSkill} as ISkill),
    // new Skill({Description: "Melee (Basic)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Brawling)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Cavalry)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Fencing)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Flail)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Parry)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Pole-Arm)", CharacteristicType: CharacteristicType.WeaponSkill}),
    // new Skill({Description: "Melee (Two-Handed)", CharacteristicType: CharacteristicType.WeaponSkill}),
    new Skill({Description: "Navigation", CharacteristicType: CharacteristicType.Initiative} as ISkill),
    new Skill({Description: "Outdoor Survival", CharacteristicType: CharacteristicType.Intelligence} as ISkill),
    new Skill({Description: "Perception", CharacteristicType: CharacteristicType.Initiative} as ISkill),
    new Skill({Description: "Ride", CharacteristicType: CharacteristicType.Agility} as ISkill),
    // new Skill({Description: "Ride (Demigryph)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Ride (Great Wolf)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Ride (Griffon)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Ride (Horse)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Ride (Pegasus)", CharacteristicType: CharacteristicType.Agility}),
    new Skill({Description: "Row", CharacteristicType: CharacteristicType.Strength} as ISkill),
    new Skill({Description: "Stealth", CharacteristicType: CharacteristicType.Agility} as ISkill),
    // new Skill({Description: "Stealth (Rural)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Stealth (Underground)", CharacteristicType: CharacteristicType.Agility}),
    // new Skill({Description: "Stealth (Urban)", CharacteristicType: CharacteristicType.Agility}),
  ]
}
